### ISSUE TITLE
tracking issue for missing netlink-packet message types for the route protocol

### ISSUE THREAD

**Issue by little-dude** [little-dude/netlink#25]
Two big pieces are missing in `netlink-packet`:

- [x] route messages (`rtmsg`). See the `pyroute2` implementation here: https://github.com/svinota/pyroute2/blob/master/pyroute2/netlink/rtnl/rtmsg.py
- [x] rule messages (`fibmsg`). This one seems a bit easier. See the `pyroute2` implementation here: https://github.com/svinota/pyroute2/blob/master/pyroute2/netlink/rtnl/fibmsg.py
- [x] tc messages. Work started in https://github.com/little-dude/netlink/pull/15
- [x] neighbour messages. Work started in https://github.com/little-dude/netlink/pull/24
- [x] namespace messages
